/* CMBC all-ages, mobile-first ease-of-use layer. */
(() => {
  if(window.__CMBC_EASE__)return;window.__CMBC_EASE__=true;
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const root=document.documentElement,body=document.body,state={scale:1,calm:false,read:false};
  try{Object.assign(state,JSON.parse(localStorage.getItem('cmbc-ease-v1')||'{}'))}catch(_){}
  const save=()=>{try{localStorage.setItem('cmbc-ease-v1',JSON.stringify(state))}catch(_){}};
  const apply=()=>{root.style.setProperty('--cmbc-user-scale',String(state.scale));body.classList.toggle('cmbc-calm',state.calm);body.classList.toggle('cmbc-high-read',state.read);$('#cmbcCalm')?.setAttribute('aria-pressed',String(state.calm));$('#cmbcRead')?.setAttribute('aria-pressed',String(state.read));};
  function firstVisit(){let seen=false;try{seen=localStorage.getItem('cmbc-welcome-seen-v2')==='1'}catch(_){}if(seen||$('#cmbcFirstVisit'))return;const wrap=document.createElement('section');wrap.id='cmbcFirstVisit';wrap.className='cmbc-first-visit';wrap.setAttribute('aria-label','First visit quick start');wrap.innerHTML=`<div class="cmbc-first-inner"><button type="button" class="cmbc-first-close" aria-label="Dismiss welcome">×</button><div class="cmbc-first-copy"><small>👋 FIRST TIME HERE?</small><h2>Welcome to CMBC</h2><p>Everything most visitors need is right here. Pick where you want to go.</p></div><div class="cmbc-first-actions"><a href="#times">⛪ <b>Service Times</b><span>Sunday & Wednesday</span></a><a href="#featured-event">🚒 <b>Fire Safety</b><span>Sept. 25 • Free food</span></a><a href="#visit">📍 <b>Plan a Visit</b><span>Address & directions</span></a><a href="#prayer">🙏 <b>Prayer</b><span>Send a request</span></a></div></div>`;const anchor=$('.headline-bar')||$('.sports-ticker')||$('.hero')||body.firstElementChild;anchor?.insertAdjacentElement('afterend',wrap);const finish=()=>{wrap.remove();try{localStorage.setItem('cmbc-welcome-seen-v2','1')}catch(_){}};wrap.querySelector('.cmbc-first-close').onclick=finish;wrap.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{try{localStorage.setItem('cmbc-welcome-seen-v2','1')}catch(_){}}));}
  function tools(){const toggle=document.createElement('button');toggle.className='cmbc-tools-toggle';toggle.type='button';toggle.id='cmbcToolsToggle';toggle.setAttribute('aria-label','Reading and accessibility tools');toggle.setAttribute('aria-expanded','false');toggle.textContent='Aa';const panel=document.createElement('aside');panel.className='cmbc-tools';panel.id='cmbcTools';panel.innerHTML=`<h3>👓 Make this easier to read</h3><p>Your choices stay on this device.</p><div class="cmbc-tools-grid"><button id="cmbcSmaller">A−</button><button id="cmbcResetText">A</button><button id="cmbcLarger">A+</button><button class="wide" id="cmbcRead" aria-pressed="false">📖 Extra-readable text</button><button class="wide" id="cmbcCalm" aria-pressed="false">🕊️ Less motion</button></div>`;body.append(panel,toggle);const close=()=>{panel.classList.remove('open');toggle.setAttribute('aria-expanded','false')};toggle.onclick=()=>{const o=panel.classList.toggle('open');toggle.setAttribute('aria-expanded',String(o))};$('#cmbcSmaller').onclick=()=>{state.scale=Math.max(.9,state.scale-.1);save();apply()};$('#cmbcResetText').onclick=()=>{state.scale=1;save();apply()};$('#cmbcLarger').onclick=()=>{state.scale=Math.min(1.3,state.scale+.1);save();apply()};$('#cmbcRead').onclick=()=>{state.read=!state.read;save();apply()};$('#cmbcCalm').onclick=()=>{state.calm=!state.calm;save();apply()};document.addEventListener('pointerdown',e=>{if(panel.classList.contains('open')&&!panel.contains(e.target)&&e.target!==toggle)close()});}
  function phoneDock(){if($('.cmbc-phone-dock'))return;const nav=document.createElement('nav');nav.className='cmbc-phone-dock';nav.setAttribute('aria-label','Quick mobile navigation');nav.innerHTML=`<a href="#top"><i>🏠</i><span>Home</span></a><a href="#featured-event"><i>🚒</i><span>Event</span></a><a href="#times"><i>⛪</i><span>Services</span></a><a href="#prayer"><i>🙏</i><span>Prayer</span></a><a href="#visit"><i>📍</i><span>Visit</span></a>`;body.appendChild(nav);}
  function backToTop(){const b=document.createElement('button');b.type='button';b.className='cmbc-top';b.setAttribute('aria-label','Back to top');b.textContent='↑';body.appendChild(b);b.onclick=()=>$('#top')?.scrollIntoView({behavior:state.calm?'auto':'smooth'});const paint=()=>b.classList.toggle('show',scrollY>900);addEventListener('scroll',paint,{passive:true});paint();}
  function activeNav(){const links=$$('a[href^="#"]').filter(a=>a.getAttribute('href').length>1),byId=new Map();links.forEach(a=>{const id=a.hash.slice(1);if(!byId.has(id))byId.set(id,[]);byId.get(id).push(a)});const sections=[...byId.keys()].map(id=>document.getElementById(id)).filter(Boolean);if(!sections.length)return;const obs=new IntersectionObserver(es=>{const hit=es.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!hit)return;links.forEach(a=>a.removeAttribute('aria-current'));(byId.get(hit.target.id)||[]).forEach(a=>a.setAttribute('aria-current','page'));},{rootMargin:'-25% 0px -60%',threshold:[0,.2,.5]});sections.forEach(s=>obs.observe(s));}
  function polish(){ $$('form').forEach(f=>{f.addEventListener('invalid',e=>e.target.setAttribute('aria-invalid','true'),true);f.addEventListener('input',e=>e.target.removeAttribute?.('aria-invalid'))});$$('a[href^="#"]').forEach(a=>a.addEventListener('click',()=>{$('#mobileMenu')?.classList.remove('open')}));}
  const run=()=>{firstVisit();tools();phoneDock();backToTop();polish();apply();setTimeout(activeNav,900)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();
})();