(async function(){
 if(document.getElementById('kids-corner'))return;
 const anchor=document.getElementById('byf')||document.getElementById('prayer'); if(!anchor)return;
 const fallback={id:'2026-09-fall-praise',month:'September 2026',theme:'Fall Praise',verseReference:'Psalm 100:4 KJV',verseText:'Enter into his gates with thanksgiving, and into his courts with praise: be thankful unto him, and bless his name.',intro:"September is here! Celebrate fall, praise God, open your Bible, get moving, and enjoy this month's brand-new coloring page and activity sheet.",read:{title:'Open Your Bible',text:'Find Psalm 100:4-5. Read it out loud with somebody in your family.',button:'I READ IT! ✓'},move:{title:'Fall Praise Moves',text:'Do 3 praise jumps, 3 big claps, and 3 reaches toward the sky. Then say: Praise God!',button:'I MOVED IT! ✓'},learn:{title:'Bible Challenge',question:'According to Psalm 100:4, how should we enter His gates and His courts?',answer:'With thanksgiving and with praise! 🙌',button:'I LEARNED IT! ✓'},coloringImage:'images/kids-september-2026-coloring.png',activityImage:'images/kids-september-2026-activity.png',artistWallMessage:"September's fall coloring page and Bible activity are here!",completionMessage:'🏆 September Bible Adventure Complete! Great job!'};
 let c=fallback,archive=[];
 try{const r=await fetch('kids-monthly.json?v='+Date.now(),{cache:'no-store'});if(r.ok)c={...fallback,...await r.json()}}catch(e){}
 try{const r=await fetch('kids-archive.json?v='+Date.now(),{cache:'no-store'});if(r.ok)archive=(await r.json()).archive||[]}catch(e){}
 const archiveHtml=archive.length?`<div class="kids-archive" style="margin-top:34px"><h3>📚 Kids Corner Archive</h3><p>Missed a month? Previous CMBC coloring pages and activity sheets stay here for families to enjoy anytime.</p><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px;margin-top:16px">${archive.map(a=>`<article style="background:#fff;border:2px solid #e5e7eb;border-radius:16px;padding:16px;color:#0f172a"><b style="font-size:1.05rem">🗓️ ${a.month}</b><span style="display:block;margin:4px 0 12px;color:#475569">${a.theme} • ${a.verseReference}</span><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><a href="${a.coloringImage}" target="_blank" rel="noopener" style="text-align:center;padding:10px;border-radius:10px;background:#e0f2fe;font-weight:800">🎨 Coloring</a><a href="${a.activityImage}" target="_blank" rel="noopener" style="text-align:center;padding:10px;border-radius:10px;background:#dcfce7;font-weight:800">✏️ Activity</a></div></article>`).join('')}</div></div>`:'';
 const section=document.createElement('section'); section.id='kids-corner'; section.className='section';
 section.innerHTML=`<div class="container kids-wrap"><span class="kids-kicker">🧒 CMBC KIDS CORNER • ${c.month.toUpperCase()} BIBLE ADVENTURE</span><h2 class="kids-title">${c.theme.toUpperCase()}<br><span>READ IT. MOVE IT. LIVE IT.</span></h2><p class="kids-intro">${c.intro}</p><div class="kids-progress"><div class="kids-progress-top"><span>🏆 THIS MONTH'S BIBLE ADVENTURE</span><span id="kidsScore">0 of 3 missions complete</span></div><div class="kids-bar"><i id="kidsBar"></i></div></div><div class="kids-mission"><article class="kids-card" data-kid="read"><div class="kids-step">1</div><h3>📖 READ — ${c.read.title}</h3><p>${c.read.text}</p><button type="button" data-kids-complete="read">${c.read.button}</button></article><article class="kids-card" data-kid="move"><div class="kids-step">2</div><h3>🏃 MOVE — ${c.move.title}</h3><p>${c.move.text}</p><button type="button" data-kids-complete="move">${c.move.button}</button></article><article class="kids-card" data-kid="learn"><div class="kids-step">3</div><h3>🧠 LEARN — ${c.learn.title}</h3><p><b>Challenge:</b> ${c.learn.question}</p><button type="button" id="kidsAnswer">SHOW THE ANSWER</button><p id="kidsAnswerText" hidden><b>Answer:</b> ${c.learn.answer}</p><button type="button" data-kids-complete="learn">${c.learn.button}</button></article></div><div class="kids-verse"><small>✨ MEMORY VERSE OF THE MONTH ✨</small><blockquote>“${c.verseText}”</blockquote><b>${c.verseReference}</b></div><div class="kids-print-zone"><h3>🍂 This Month's NEW Printables</h3><p>Two fresh pages every month — made for CMBC kids and families.</p><div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;max-width:860px;margin:18px auto"><img src="${c.coloringImage}" alt="${c.month} CMBC Kids Corner coloring page" style="display:block;width:100%;border-radius:14px;box-shadow:0 8px 24px rgba(0,0,0,.14)"><img src="${c.activityImage}" alt="${c.month} CMBC Kids Corner activity sheet" style="display:block;width:100%;border-radius:14px;box-shadow:0 8px 24px rgba(0,0,0,.14)"></div><div class="kids-print-buttons"><button class="kids-print" id="kidsPrintColor" type="button">🖨️ PRINT COLORING PAGE</button><button class="kids-print" id="kidsPrintActivity" type="button">📖 PRINT ACTIVITY SHEET</button><button class="kids-print" id="kidsPrintBoth" type="button">⭐ PRINT BOTH PAGES</button></div><br><span class="artist-wall">🎨 ${c.artistWallMessage}</span>${archiveHtml}</div></div>`;
 anchor.parentNode.insertBefore(section,anchor);
 const storageKey='cmbcKidsAdventure:'+c.id; const saved=JSON.parse(localStorage.getItem(storageKey)||'{}'); const toast=document.createElement('div');toast.className='kids-toast';document.body.appendChild(toast);
 function pop(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)}
 function paint(){const keys=['read','move','learn'];let n=0;keys.forEach(k=>{const card=section.querySelector(`[data-kid="${k}"]`);if(saved[k]){n++;card?.classList.add('done')}});section.querySelector('#kidsScore').textContent=`${n} of 3 missions complete`;section.querySelector('#kidsBar').style.width=(n/3*100)+'%';if(n===3)pop(c.completionMessage)}
 section.querySelectorAll('[data-kids-complete]').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.kidsComplete;saved[k]=true;localStorage.setItem(storageKey,JSON.stringify(saved));paint();pop('⭐ Mission complete! Great job!')}));
 section.querySelector('#kidsAnswer')?.addEventListener('click',()=>{const a=section.querySelector('#kidsAnswerText');a.hidden=!a.hidden});
 const printImage=(src)=>{const w=window.open(src,'_blank','noopener');if(!w)pop('Please allow pop-ups to open the printable.')};
 section.querySelector('#kidsPrintColor')?.addEventListener('click',()=>printImage(c.coloringImage));
 section.querySelector('#kidsPrintActivity')?.addEventListener('click',()=>printImage(c.activityImage));
 section.querySelector('#kidsPrintBoth')?.addEventListener('click',()=>window.open(`kids-print.html?print=all&color=${encodeURIComponent(c.coloringImage)}&activity=${encodeURIComponent(c.activityImage)}`,'_blank','noopener'));
 paint();
})();