(async function(){
 if(document.getElementById('kids-corner'))return;
 const anchor=document.getElementById('byf')||document.getElementById('prayer'); if(!anchor)return;
 const fallback={id:'2026-09-strength-peace',month:'September 2026',theme:'Strength & Peace',verseReference:'Psalm 29:11 KJV',verseText:'The LORD will give strength unto his people; the LORD will bless his people with peace.',intro:"September is here! Open your Bible, learn God's Word, get moving, and complete this month's three Bible Adventure missions. New coloring and activity pages are coming this month!",read:{title:'Open Your Bible',text:'Find Psalm 29:11. Read it out loud with somebody in your family. What two gifts does the LORD give His people?',button:'I READ IT! ✓'},move:{title:'Strong & Steady',text:'Stand tall and strong for 10 seconds, take 3 slow peaceful breaths, then say: The LORD gives strength and peace!',button:'I MOVED IT! ✓'},learn:{title:'Bible Challenge',question:'According to Psalm 29:11, what will the LORD give His people and what will He bless them with?',answer:'Strength and peace! 🙌',button:'I LEARNED IT! ✓'},coloringImage:'images/kidscornercolorpage1.png',activityImage:'images/kidscorneractivitypage1.png',artistWallMessage:'New September coloring and activity pages are coming soon!',completionMessage:'🏆 September Bible Adventure Complete! Great job!'};
 let c=fallback;
 try{const r=await fetch('kids-monthly.json?v='+Date.now(),{cache:'no-store'});if(r.ok)c={...fallback,...await r.json()}}catch(e){}
 const section=document.createElement('section'); section.id='kids-corner'; section.className='section';
 section.innerHTML=`<div class="container kids-wrap"><span class="kids-kicker">🧒 CMBC KIDS CORNER • ${c.month.toUpperCase()} BIBLE ADVENTURE</span><h2 class="kids-title">${c.theme.toUpperCase()}<br><span>READ IT. MOVE IT. LIVE IT.</span></h2><p class="kids-intro">${c.intro}</p><div class="kids-progress"><div class="kids-progress-top"><span>🏆 THIS MONTH'S BIBLE ADVENTURE</span><span id="kidsScore">0 of 3 missions complete</span></div><div class="kids-bar"><i id="kidsBar"></i></div></div><div class="kids-mission"><article class="kids-card" data-kid="read"><div class="kids-step">1</div><h3>📖 READ — ${c.read.title}</h3><p>${c.read.text}</p><button type="button" data-kids-complete="read">${c.read.button}</button></article><article class="kids-card" data-kid="move"><div class="kids-step">2</div><h3>🏃 MOVE — ${c.move.title}</h3><p>${c.move.text}</p><button type="button" data-kids-complete="move">${c.move.button}</button></article><article class="kids-card" data-kid="learn"><div class="kids-step">3</div><h3>🧠 LEARN — ${c.learn.title}</h3><p><b>Challenge:</b> ${c.learn.question}</p><button type="button" id="kidsAnswer">SHOW THE ANSWER</button><p id="kidsAnswerText" hidden><b>Answer:</b> ${c.learn.answer}</p><button type="button" data-kids-complete="learn">${c.learn.button}</button></article></div><div class="kids-verse"><small>✨ MEMORY VERSE OF THE MONTH ✨</small><blockquote>“${c.verseText}”</blockquote><b>${c.verseReference}</b></div><div class="kids-print-zone"><h3>🖍️ This Month's Printables</h3><p>Color, create, and explore God's Word with this month's Kids Corner pages.</p><div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;max-width:860px;margin:18px auto"><img src="${c.coloringImage}" alt="CMBC Kids Corner coloring page" style="display:block;width:100%;border-radius:14px;box-shadow:0 8px 24px rgba(0,0,0,.14)"><img src="${c.activityImage}" alt="CMBC Kids Corner activity sheet" style="display:block;width:100%;border-radius:14px;box-shadow:0 8px 24px rgba(0,0,0,.14)"></div><div class="kids-print-buttons"><button class="kids-print" id="kidsPrintColor" type="button">🖨️ PRINT COLORING PAGE</button><button class="kids-print" id="kidsPrintActivity" type="button">📖 PRINT ACTIVITY SHEET</button><button class="kids-print" id="kidsPrintBoth" type="button">⭐ PRINT BOTH PAGES</button></div><br><span class="artist-wall">🎨 ${c.artistWallMessage}</span></div></div>`;
 anchor.parentNode.insertBefore(section,anchor);
 const storageKey='cmbcKidsAdventure:'+c.id;
 const saved=JSON.parse(localStorage.getItem(storageKey)||'{}');
 const toast=document.createElement('div');toast.className='kids-toast';document.body.appendChild(toast);
 function pop(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)}
 function paint(){const keys=['read','move','learn'];let n=0;keys.forEach(k=>{const card=section.querySelector(`[data-kid="${k}"]`);if(saved[k]){n++;card?.classList.add('done')}});section.querySelector('#kidsScore').textContent=`${n} of 3 missions complete`;section.querySelector('#kidsBar').style.width=(n/3*100)+'%';if(n===3)pop(c.completionMessage)}
 section.querySelectorAll('[data-kids-complete]').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.kidsComplete;saved[k]=true;localStorage.setItem(storageKey,JSON.stringify(saved));paint();pop('⭐ Mission complete! Great job!')}));
 section.querySelector('#kidsAnswer')?.addEventListener('click',()=>{const a=section.querySelector('#kidsAnswerText');a.hidden=!a.hidden});
 const openPrint=(mode)=>{window.open('kids-print.html?print='+mode,'_blank','noopener')};
 section.querySelector('#kidsPrintColor')?.addEventListener('click',()=>openPrint('color'));
 section.querySelector('#kidsPrintActivity')?.addEventListener('click',()=>openPrint('activity'));
 section.querySelector('#kidsPrintBoth')?.addEventListener('click',()=>openPrint('all'));
 paint();
})();