const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const progress=$('#scrollProgress');function drawProgress(){const d=document.documentElement,max=d.scrollHeight-d.clientHeight;progress.style.width=(max?Math.min(100,d.scrollTop/max*100):0)+'%'}addEventListener('scroll',drawProgress,{passive:true});drawProgress();
const menuBtn=$('#menuBtn'),mobileMenu=$('#mobileMenu');menuBtn?.addEventListener('click',()=>{const open=mobileMenu.classList.toggle('open');menuBtn.setAttribute('aria-expanded',String(open));menuBtn.textContent=open?'✕':'☰'});$$('#mobileMenu a').forEach(a=>a.addEventListener('click',()=>{mobileMenu.classList.remove('open');menuBtn.textContent='☰';menuBtn.setAttribute('aria-expanded','false')}));
const revealObserver=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');revealObserver.unobserve(e.target)}}),{threshold:.1});$$('.reveal').forEach(el=>revealObserver.observe(el));

/* Reliable continuous CMBC LIVE ticker */
const tickerTrack=$('#tickerTrack'),tickerGroup=$('#tickerGroup');if(tickerTrack&&tickerGroup){let x=0,last=performance.now(),width=0;const clone=tickerGroup.cloneNode(true);clone.removeAttribute('id');clone.setAttribute('aria-hidden','true');tickerTrack.appendChild(clone);const measure=()=>{width=tickerGroup.scrollWidth};measure();addEventListener('resize',measure);new ResizeObserver(measure).observe(tickerGroup);function frame(now){const dt=Math.min(60,now-last);last=now;if(width>0){x-=dt*.06;if(-x>=width)x+=width;tickerTrack.style.transform=`translate3d(${x}px,0,0)`}requestAnimationFrame(frame)}requestAnimationFrame(frame)}

/* Smart next-event engine */
let scheduleData=null;async function loadSchedule(){try{const r=await fetch('events.json?ts='+Date.now(),{cache:'no-store'});if(r.ok)scheduleData=await r.json()}catch(e){}if(!scheduleData)scheduleData={featured:{title:'Church Picnic',start:'2026-08-23T11:00:00-04:00',location:'Location TBA',summary:'Bring a dish • Kids activities • Rain or shine',anchor:'#picnic'},weekly:[{day:0,hour:10,minute:0,title:'Sunday School',details:'Sunday • 10:00 AM',anchor:'#times'},{day:0,hour:11,minute:0,title:'Morning Worship',details:'Sunday • 11:00 AM',anchor:'#times'},{day:3,hour:18,minute:25,title:'BYF Youth Service',details:'Wednesday • 6:25 PM',anchor:'#byf'},{day:3,hour:19,minute:0,title:'Adult Bible Study',details:'Wednesday • 7:00 PM',anchor:'#times'}]};setupFeatured();updateNext();}
function nextWeekly(item,now=new Date()){const d=new Date(now);let add=(item.day-d.getDay()+7)%7;d.setDate(d.getDate()+add);d.setHours(item.hour,item.minute,0,0);if(d<=now){d.setDate(d.getDate()+7)}return d}
function chooseNext(){const now=new Date(),c=[];(scheduleData.weekly||[]).forEach(w=>c.push({...w,date:nextWeekly(w,now),special:false}));if(scheduleData.featured){const fd=new Date(scheduleData.featured.start);if(fd>now)c.push({title:scheduleData.featured.title,details:`${fd.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})} • ${fd.toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})} • ${scheduleData.featured.location}`,anchor:scheduleData.featured.anchor||'#calendar',date:fd,special:true})}c.sort((a,b)=>a.date-b.date);return c[0]}
function durationParts(ms){ms=Math.max(0,ms);const days=Math.floor(ms/86400000);ms%=86400000;const hours=Math.floor(ms/3600000);ms%=3600000;const minutes=Math.floor(ms/60000);ms%=60000;const seconds=Math.floor(ms/1000);return{days,hours,minutes,seconds}}
function renderCount(el,p){if(!el)return;el.innerHTML=`<div><b>${String(p.days).padStart(2,'0')}</b><span>Days</span></div><div><b>${String(p.hours).padStart(2,'0')}</b><span>Hours</span></div><div><b>${String(p.minutes).padStart(2,'0')}</b><span>Minutes</span></div><div><b>${String(p.seconds).padStart(2,'0')}</b><span>Seconds</span></div>`}
function updateNext(){if(!scheduleData)return;const n=chooseNext();if(!n)return;$('#nextBadge').textContent=n.special?'⭐ FEATURED EVENT':'🔴 NEXT AT CMBC';$('#nextTitle').textContent=n.title;$('#nextDetails').textContent=n.details;const a=$('#nextAction');a.href=n.anchor||'#visit';a.textContent=n.special?'See Event Details':'Plan Your Visit';renderCount($('#nextCount'),durationParts(n.date-Date.now()))}
function setupFeatured(){const f=scheduleData.featured;if(!f)return;const d=new Date(f.start),title=$('#headlineTitle'),sub=$('#headlineSub'),link=$('#headlineLink');if(d>Date.now()){title.textContent=`🧺 ${f.title.toUpperCase()} • ${d.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}).toUpperCase()} • ${d.toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})}`;sub.textContent=`${f.location} • ${f.summary}`;link.href=f.anchor||'#calendar';$('#featuredTitle').textContent=`${f.title} • ${d.toLocaleDateString(undefined,{month:'long',day:'numeric'})}`;$('#featuredIntro').textContent=f.summary;const countdown=$('#countdown');const tick=()=>{const left=d-Date.now();if(left<=0){countdown.innerHTML='<div class="count-box"><b>🎉</b><span>Today!</span></div>';return}const p=durationParts(left);countdown.innerHTML=`<div class="count-box"><b>${String(p.days).padStart(2,'0')}</b><span>Days</span></div><div class="count-box"><b>${String(p.hours).padStart(2,'0')}</b><span>Hours</span></div><div class="count-box"><b>${String(p.minutes).padStart(2,'0')}</b><span>Minutes</span></div><div class="count-box"><b>${String(p.seconds).padStart(2,'0')}</b><span>Seconds</span></div>`};tick();setInterval(tick,1000)}}loadSchedule();setInterval(updateNext,1000);$('#nextCalendarBtn')?.addEventListener('click',()=>$('#calendar')?.scrollIntoView({behavior:'smooth'}));

/* Hymnal player: public-domain / Creative Commons recordings */
const hymns={
 'christ-arose':{title:'Christ Arose',credit:'Haydn Quartet, 1908 • Public domain',src:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Victor-16008b-b6003.ogg'},
 'blessed-assurance':{title:'Blessed Assurance',credit:'LibriVox recording • Public domain',src:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Army_and_Navy_Hymnal-0212.ogg'},
 'to-god-be-glory':{title:'To God Be the Glory',credit:'Richard MS Irwin • CC BY-SA',src:'https://commons.wikimedia.org/wiki/Special:Redirect/file/HWW_To_God_Be_The_Glory.ogg'},
 'joyful-joyful':{title:'Joyful, Joyful / Ode to Joy',credit:'CC0 public-domain dedication',src:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Odetojoy.ogg'}
};
const audio=$('#hymnAudio'),musicToggle=$('#musicToggle'),heroMusicBtn=$('#heroMusicBtn'),musicVolume=$('#musicVolume'),musicPlayer=$('#musicPlayer'),musicMinimize=$('#musicMinimize'),hymnSelect=$('#hymnSelect');let musicOn=false,blocked=false,currentHymn='christ-arose';
function loadHymn(key,autoplay=false){const h=hymns[key]||hymns['christ-arose'];currentHymn=key;$('#musicTitle').textContent=h.title;$('#musicCredit').textContent=h.credit;if(heroMusicBtn)heroMusicBtn.textContent=`🎵 Play ${h.title}`;if(audio){const wasPlaying=musicOn;audio.src=h.src;audio.load();if(autoplay||wasPlaying)playMusic()}}
function musicUI(){if(musicToggle){musicToggle.textContent=musicOn?'❚❚':'▶';musicToggle.setAttribute('aria-pressed',String(musicOn))}if(heroMusicBtn){const t=hymns[currentHymn].title;heroMusicBtn.textContent=musicOn?`⏸ Pause ${t}`:`🎵 Play ${t}`}}
async function playMusic(){if(!audio)return false;try{audio.volume=musicVolume?Number(musicVolume.value):.28;await audio.play();musicOn=true;blocked=false;musicUI();return true}catch(e){musicOn=false;blocked=true;musicUI();return false}}
function pauseMusic(){audio?.pause();musicOn=false;musicUI()}async function toggleMusic(){musicOn?pauseMusic():await playMusic()}musicToggle?.addEventListener('click',toggleMusic);heroMusicBtn?.addEventListener('click',toggleMusic);musicVolume?.addEventListener('input',()=>{if(audio)audio.volume=Number(musicVolume.value)});musicMinimize?.addEventListener('click',()=>musicPlayer?.classList.toggle('minimized'));hymnSelect?.addEventListener('change',e=>loadHymn(e.target.value,true));if(audio){audio.loop=true;audio.volume=.28;audio.addEventListener('play',()=>{musicOn=true;musicUI()});audio.addEventListener('pause',()=>{musicOn=false;musicUI()});loadHymn('christ-arose');setTimeout(playMusic,180)}const unlock=async()=>{if(blocked&&!musicOn)await playMusic();document.removeEventListener('pointerdown',unlock,true);document.removeEventListener('touchstart',unlock,true);document.removeEventListener('keydown',unlock,true)};document.addEventListener('pointerdown',unlock,true);document.addEventListener('touchstart',unlock,true);document.addEventListener('keydown',unlock,true);

/* First-time visitor guide */
const modal=$('#firstVisitModal');function openModal(){modal?.classList.add('open');modal?.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function closeModal(){modal?.classList.remove('open');modal?.setAttribute('aria-hidden','true');document.body.style.overflow=''}$('#newHereBtn')?.addEventListener('click',openModal);$('#newHereBtn2')?.addEventListener('click',openModal);$('#modalClose')?.addEventListener('click',closeModal);$('#modalTimes')?.addEventListener('click',closeModal);modal?.addEventListener('click',e=>{if(e.target===modal)closeModal()});addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();closeLightbox()}});

/* Prayer confirmation */
const q=new URLSearchParams(location.search);if(q.get('prayer')==='sent'){const form=$('#prayerForm'),thanks=$('#prayerThanks');if(form)form.hidden=true;if(thanks)thanks.hidden=false;setTimeout(()=>$('#prayer')?.scrollIntoView({behavior:'smooth'}),300)}

/* Memory wall + featured image + swipe/lightbox */
const ALBUM_LABELS={worship:'⛪ Worship & Church Services','church-family':'👨‍👩‍👧‍👦 Church Family & Fellowship','special-events':'🎉 Special Events','byf-youth':'🧒 BYF & Youth'};let manifest=[],visiblePhotos=[],lightboxIndex=0;async function getManifest(){if(manifest.length)return manifest;const r=await fetch('gallery-manifest.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('manifest');const data=await r.json();manifest=Array.isArray(data.photos)?data.photos:[];return manifest}const gallery=$('#galleryLive');async function loadGallery(album='all'){if(!gallery)return;$$('.album-card,.gallery-all').forEach(b=>b.classList.toggle('active',b.dataset.album===album));gallery.innerHTML='<div class="gallery-status">📸 Loading our church memories…</div>';try{const all=await getManifest();visiblePhotos=(album==='all'?all:all.filter(x=>x.album===album)).filter(x=>/\.(jpe?g|png|webp|gif)$/i.test(x.src));if(!visiblePhotos.length){gallery.innerHTML='<div class="gallery-empty">📷 More memories from this part of church life are coming soon.</div>';$('#featuredMemory').hidden=true;return}const feature=$('#featuredMemory');feature.hidden=false;feature.innerHTML=`<img src="${encodeURI(visiblePhotos[0].src)}" alt="Featured CMBC church memory">`;feature.onclick=()=>openLightboxAt(0);gallery.innerHTML='';visiblePhotos.forEach((f,i)=>{const fig=document.createElement('figure');fig.className='gallery-item';fig.tabIndex=0;const img=document.createElement('img');img.loading=i<6?'eager':'lazy';img.decoding='async';img.src=encodeURI(f.src);img.alt=(ALBUM_LABELS[f.album]||'CMBC church memory')+' — Campbell Memorial Baptist Church';const open=()=>openLightboxAt(i);fig.addEventListener('click',open);fig.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}});img.addEventListener('error',()=>fig.remove());fig.appendChild(img);gallery.appendChild(fig)})}catch(e){gallery.innerHTML='<div class="gallery-empty">📷 The Memory Wall is taking a moment to load. Please refresh and try again.</div>'}}$$('.album-card,.gallery-all').forEach(btn=>btn.addEventListener('click',()=>loadGallery(btn.dataset.album)));loadGallery('all');
const lightbox=$('#photoLightbox'),lightboxImage=$('#lightboxImage');function openLightboxAt(i){if(!lightbox||!visiblePhotos.length)return;lightboxIndex=(i+visiblePhotos.length)%visiblePhotos.length;lightboxImage.src=encodeURI(visiblePhotos[lightboxIndex].src);lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function closeLightbox(){lightbox?.classList.remove('open');lightbox?.setAttribute('aria-hidden','true');document.body.style.overflow=''}function stepLightbox(n){openLightboxAt(lightboxIndex+n)}$('#lightboxClose')?.addEventListener('click',closeLightbox);$('#lightboxPrev')?.addEventListener('click',()=>stepLightbox(-1));$('#lightboxNext')?.addEventListener('click',()=>stepLightbox(1));lightbox?.addEventListener('click',e=>{if(e.target===lightbox)closeLightbox()});let touchX=0;lightbox?.addEventListener('touchstart',e=>touchX=e.changedTouches[0].clientX,{passive:true});lightbox?.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-touchX;if(Math.abs(dx)>45)stepLightbox(dx<0?1:-1)},{passive:true});

/* PWA install */
let deferredPrompt=null;const installBtns=[$('#installBtn'),$('#installBtn2')].filter(Boolean);addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtns.forEach(b=>b.hidden=false)});installBtns.forEach(b=>b.addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtns.forEach(x=>x.hidden=true)}else if(/iphone|ipad|ipod/i.test(navigator.userAgent)){alert('On iPhone: tap the Share button, then choose “Add to Home Screen.”')}else{alert('Use your browser menu and choose “Install app” or “Add to Home screen.”')}}));if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));

/* Celebration / motion */
function confetti(count=24){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(let i=0;i<count;i++){const c=document.createElement('i');Object.assign(c.style,{position:'fixed',zIndex:'9998',top:'-18px',left:Math.random()*100+'vw',width:'9px',height:'14px',background:['#ffc83d','#fff','#55a8ff','#ff789b','#71d98f'][i%5],pointerEvents:'none',borderRadius:'2px',transform:`rotate(${Math.random()*180}deg)`,transition:`transform ${2.6+Math.random()*1.7}s linear, top ${2.6+Math.random()*1.7}s linear`});document.body.appendChild(c);requestAnimationFrame(()=>{c.style.top='110vh';c.style.transform=`translateX(${Math.random()*180-90}px) rotate(760deg)`});setTimeout(()=>c.remove(),4800)}}$$('.event-card.featured,.countdown-shell').forEach(el=>el.addEventListener('click',()=>confetti(22)));setTimeout(()=>confetti(14),850);if(matchMedia('(pointer:fine)').matches&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const heroBg=$('.hero-bg');addEventListener('scroll',()=>{if(heroBg&&scrollY<900)heroBg.style.transform=`scale(1.06) translate3d(0,${Math.min(30,scrollY*.035)}px,0)`},{passive:true})}
