const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const progress=$('#scrollProgress');function drawProgress(){const d=document.documentElement;const max=d.scrollHeight-d.clientHeight;progress.style.width=(max?Math.min(100,d.scrollTop/max*100):0)+'%'}addEventListener('scroll',drawProgress,{passive:true});drawProgress();
const menuBtn=$('#menuBtn'),mobileMenu=$('#mobileMenu');menuBtn?.addEventListener('click',()=>{const open=mobileMenu.classList.toggle('open');menuBtn.setAttribute('aria-expanded',String(open));menuBtn.textContent=open?'✕':'☰'});$$('#mobileMenu a').forEach(a=>a.addEventListener('click',()=>{mobileMenu.classList.remove('open');menuBtn.textContent='☰';menuBtn.setAttribute('aria-expanded','false')}));
const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');revealObserver.unobserve(e.target)}}),{threshold:.1});$$('.reveal').forEach(el=>revealObserver.observe(el));
const tickerTrack=$('#tickerTrack'),tickerGroup=$('#tickerGroup');let tickerX=0,tickerLast=performance.now(),tickerWidth=0,tickerPaused=false;if(tickerTrack&&tickerGroup){const clone=tickerGroup.cloneNode(true);clone.removeAttribute('id');clone.setAttribute('aria-hidden','true');tickerTrack.appendChild(clone);const measure=()=>tickerWidth=tickerGroup.getBoundingClientRect().width;measure();new ResizeObserver(measure).observe(tickerGroup);function tickerFrame(now){const dt=Math.min(50,now-tickerLast);tickerLast=now;if(!tickerPaused&&tickerWidth>0){tickerX-=dt*.055;if(-tickerX>=tickerWidth)tickerX+=tickerWidth;tickerTrack.style.transform=`translate3d(${tickerX}px,0,0)`}requestAnimationFrame(tickerFrame)}requestAnimationFrame(tickerFrame);tickerTrack.addEventListener('mouseenter',()=>tickerPaused=true);tickerTrack.addEventListener('mouseleave',()=>tickerPaused=false);document.addEventListener('visibilitychange',()=>{tickerLast=performance.now()})}
(function countdown(){const el=$('#countdown');if(!el)return;const target=new Date('2026-08-23T11:00:00-04:00').getTime();function tick(){let ms=target-Date.now();if(ms<=0){el.innerHTML='<div class="count-box"><b>🎉</b><span>Today!</span></div>';return}const d=Math.floor(ms/86400000);ms%=86400000;const h=Math.floor(ms/3600000);ms%=3600000;const m=Math.floor(ms/60000);ms%=60000;const s=Math.floor(ms/1000);el.innerHTML=`<div class="count-box"><b>${String(d).padStart(2,'0')}</b><span>Days</span></div><div class="count-box"><b>${String(h).padStart(2,'0')}</b><span>Hours</span></div><div class="count-box"><b>${String(m).padStart(2,'0')}</b><span>Minutes</span></div><div class="count-box"><b>${String(s).padStart(2,'0')}</b><span>Seconds</span></div>`}tick();setInterval(tick,1000)})();
const audio=$('#hymnAudio'),musicToggle=$('#musicToggle'),heroMusicBtn=$('#heroMusicBtn'),musicVolume=$('#musicVolume'),musicPlayer=$('#musicPlayer'),musicMinimize=$('#musicMinimize');let musicOn=false,autoplayBlocked=false;
if(audio){audio.src='https://upload.wikimedia.org/wikipedia/commons/b/bc/Victor-16008b-b6003.ogg';audio.load()}
function updateMusicUI(){if(musicToggle){musicToggle.textContent=musicOn?'❚❚':'▶';musicToggle.setAttribute('aria-pressed',String(musicOn))}if(heroMusicBtn)heroMusicBtn.textContent=musicOn?'⏸ Pause Christ Arose':'🎵 Play Christ Arose'}
async function playMusic(){if(!audio)return false;try{audio.volume=musicVolume?Number(musicVolume.value):.28;await audio.play();musicOn=true;autoplayBlocked=false;updateMusicUI();return true}catch(e){musicOn=false;autoplayBlocked=true;updateMusicUI();return false}}
function pauseMusic(){audio?.pause();musicOn=false;updateMusicUI()}async function toggleMusic(){musicOn?pauseMusic():await playMusic()}musicToggle?.addEventListener('click',toggleMusic);heroMusicBtn?.addEventListener('click',toggleMusic);musicVolume?.addEventListener('input',()=>{if(audio)audio.volume=Number(musicVolume.value)});musicMinimize?.addEventListener('click',()=>musicPlayer?.classList.toggle('minimized'));
if(audio){audio.volume=.28;audio.addEventListener('play',()=>{musicOn=true;updateMusicUI()});audio.addEventListener('pause',()=>{musicOn=false;updateMusicUI()});audio.addEventListener('ended',()=>{audio.currentTime=0;playMusic()});setTimeout(playMusic,120)}
const firstGesture=async()=>{if(autoplayBlocked&&!musicOn)await playMusic();document.removeEventListener('pointerdown',firstGesture,true);document.removeEventListener('touchstart',firstGesture,true);document.removeEventListener('keydown',firstGesture,true)};document.addEventListener('pointerdown',firstGesture,true);document.addEventListener('touchstart',firstGesture,true);document.addEventListener('keydown',firstGesture,true);
const ALBUM_LABELS={worship:'⛪ Worship & Church Services','church-family':'👨‍👩‍👧‍👦 Church Family & Fellowship','special-events':'🎉 Special Events','byf-youth':'🧒 BYF & Youth'};let manifest=[];async function getManifest(){if(manifest.length)return manifest;const r=await fetch('gallery-manifest.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('manifest');const data=await r.json();manifest=Array.isArray(data.photos)?data.photos:[];return manifest}const gallery=$('#galleryLive');async function loadGallery(album='all'){if(!gallery)return;$$('.album-card,.gallery-all').forEach(b=>b.classList.toggle('active',b.dataset.album===album));gallery.innerHTML='<div class="gallery-status">📸 Loading our church memories…</div>';try{const all=await getManifest();const imgs=(album==='all'?all:all.filter(x=>x.album===album)).filter(x=>/\.(jpe?g|png|webp|gif)$/i.test(x.src));if(!imgs.length){gallery.innerHTML='<div class="gallery-empty">📷 More memories from this part of church life are coming soon.</div>';return}gallery.innerHTML='';imgs.forEach((f,i)=>{const fig=document.createElement('figure');fig.className='gallery-item';fig.tabIndex=0;const img=document.createElement('img');img.loading=i<6?'eager':'lazy';img.decoding='async';img.src=encodeURI(f.src);img.alt=(ALBUM_LABELS[f.album]||'CMBC church memory')+' — Campbell Memorial Baptist Church';const open=()=>openLightbox(img.src);fig.addEventListener('click',open);fig.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}});img.addEventListener('error',()=>fig.remove());fig.appendChild(img);gallery.appendChild(fig)})}catch(e){gallery.innerHTML='<div class="gallery-empty">📷 The Memory Wall is taking a moment to load. Please refresh and try again.</div>'}}$$('.album-card,.gallery-all').forEach(btn=>btn.addEventListener('click',()=>loadGallery(btn.dataset.album)));loadGallery('all');
const lightbox=$('#photoLightbox'),lightboxImage=$('#lightboxImage');function openLightbox(src){if(!lightbox)return;lightboxImage.src=src;lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function closeLightbox(){lightbox?.classList.remove('open');lightbox?.setAttribute('aria-hidden','true');document.body.style.overflow=''}$('#lightboxClose')?.addEventListener('click',closeLightbox);lightbox?.addEventListener('click',e=>{if(e.target===lightbox)closeLightbox()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeLightbox()});
function confetti(count=26){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(let i=0;i<count;i++){const c=document.createElement('i');Object.assign(c.style,{position:'fixed',zIndex:'9998',top:'-18px',left:Math.random()*100+'vw',width:'9px',height:'14px',background:['#ffc83d','#fff','#55a8ff','#ff789b','#71d98f'][i%5],pointerEvents:'none',borderRadius:'2px',transform:`rotate(${Math.random()*180}deg)`,transition:`transform ${2.6+Math.random()*1.7}s linear, top ${2.6+Math.random()*1.7}s linear`});document.body.appendChild(c);requestAnimationFrame(()=>{c.style.top='110vh';c.style.transform=`translateX(${Math.random()*180-90}px) rotate(760deg)`});setTimeout(()=>c.remove(),4800)}}$$('.event-card.featured,.countdown-shell').forEach(el=>el.addEventListener('click',()=>confetti(22)));setTimeout(()=>confetti(16),800);
if(matchMedia('(pointer:fine)').matches&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const heroBg=$('.hero-bg');addEventListener('scroll',()=>{if(heroBg&&scrollY<900)heroBg.style.transform=`scale(1.06) translate3d(0,${Math.min(28,scrollY*.035)}px,0)`},{passive:true})}